# Generated by Django 3.1.7 on 2021-04-05 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=25)),
                ('question', models.TextField()),
                ('counter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=25)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('counter', models.IntegerField()),
                ('linkedTopic', models.ManyToManyField(to='appix.Tag')),
                ('subjectName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appix.subject')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=25)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('counter', models.IntegerField()),
                ('linkedTopic', models.ManyToManyField(to='appix.Tag')),
                ('subjectName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appix.subject')),
            ],
        ),
        migrations.CreateModel(
            name='InLineImagexCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAnswer', models.BooleanField(default=False)),
                ('images', models.FileField(blank=True, upload_to='images/')),
                ('card', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appix.imagecard')),
            ],
        ),
        migrations.AddField(
            model_name='imagecard',
            name='linkedTopic',
            field=models.ManyToManyField(to='appix.Tag'),
        ),
        migrations.AddField(
            model_name='imagecard',
            name='subjectName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appix.subject'),
        ),
    ]
