# Generated by Django 3.1.7 on 2021-04-06 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InLineChoicexCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=150)),
                ('isAnswer', models.BooleanField(default=False)),
                ('images', models.FileField(blank=True, upload_to='images/')),
                ('card', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appix.multiplechoicecard')),
            ],
        ),
    ]
