# Generated by Django 3.1.7 on 2021-04-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appix', '0003_auto_20210408_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(default='Write here your answer...'),
        ),
    ]
